#!/bin/bash

process_cmd()
{
    local total_args=$#
    local show_help_arg=false
    local build_ninja_project_arg=false
    local build_vs2019_project_arg=false

    while [[ $# > 0 ]]
    do
        case $1 in
            -h|--help)
                show_help_arg=true
            ;;
            --ninja)
                build_ninja_project_arg=true
            ;;
            --vs2019)
                build_vs2019_project_arg=true
            ;;
        esac
        shift
    done

    if [[ $show_help_arg == true ]] || [[ $total_args == 0 ]]
    then
        show_help
    else
        main
    fi

    exit 0
}


main()
{
    if [[ $build_ninja_project_arg == true && $build_vs2019_project_arg == true ]]
    then
        echo "The supplied arguments '--ninja' and '--vs2019' are mutually exclusive."
        exit -1
    fi

    if [[ $build_for_os == windows ]]
    then
        root_path=`cygpath -w "$root_path"`
    fi

    local base_path="${root_path}build/${build_for_os:0:3}_${build_for_arch}_${build_for_type}_${build_for_link}"
    local projects_folder="projects"

    if [[ $build_ninja_project_arg == true ]]
    then
        local project_type='ninja'
        build_project
    elif [[ $build_vs2019_project_arg == true ]]
    then
        local project_type='vs2019'
        build_project
    else
        echo 'An invalid argument was supplied!'
    fi
}


build_project()
{
    project_path="$base_path/$projects_folder/$project_type"
    if [[ -d $project_path ]]
    then
        meson compile -C "$project_path"
        meson install --only-changed -C "$project_path"
    else
        echo 'Project not configured. First configure the project before executing this command.'
    fi
}


show_help()
{
    script_name=$(basename "$0")
    echo "#######################################################################"
    echo "#                                                                     #"
    echo "#                        PROJECT BUILDER                              #"
    echo "#                                                                     #"
    echo "# USAGE:                                                              #"
    echo "#     $script_name {-h|--help | [--ninja] [--vs2019]}              #"
    echo "#                                                                     #"
    echo "# ARGUMENTS:                                                          #"
    echo "#     -h|--help    Print this help and exit.                          #"
    echo "#                                                                     #"
    echo "#     --ninja    Build Ninja projects.                                #"
    echo "#                                                                     #"
    echo "#     --vs2019    Build Visual Studio 2019 projects.                  #"
    echo "#                                                                     #"
    echo "#######################################################################"
}


command_line_args=("$@")
process_cmd ${command_line_args[@]}
