#!/bin/bash



process_cmd()
{
    local show_help_arg=false
    local build_ninja_project_arg=false
    local build_vs2019_project_arg=false
    local total_args="$#"

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -h|--help) 
                show_help_arg=true 
            ;;
            --ninja)   
                build_ninja_project_arg=true 
            ;;
            --vs2019)  
                build_vs2019_project_arg=true 
            ;;
        esac
        shift
    done

    if [ $show_help_arg = true ] || [ $total_args -eq 0 ]
    then
        show_help
    elif [ $build_ninja_project_arg = true ] || [ $build_vs2019_project_arg = true ]
    then
        main $build_ninja_project_arg $build_vs2019_project_arg
    fi

    exit 0
}



main()
{
    local build_ninja_project_arg=$1
    local build_vs2019_project_arg=$2

    if [ $build_for_os = windows ]; then
        current_folder=`cygpath -w $current_folder`
    fi
    
    local base_path="${current_folder}build/$build_for_os/$build_for_arch/$build_for_type"
    local projects_folder="projects"
    
    if [ $build_ninja_project_arg = true ]
    then
        build_ninja_project $base_path $projects_folder 
    fi

    if [ $build_vs2019_project_arg = true ]
    then
        build_vs2019_project $base_path $projects_folder 
    fi
}



build_ninja_project()
{
    local base_path=$1
    local projects_folder=$2

    ninja_project_folder=$base_path/$projects_folder/ninja
    if [ -d "$ninja_project_folder" ] 
    then
        meson compile -C $ninja_project_folder 
        meson install --only-changed -C $ninja_project_folder 
    fi
}



build_vs2019_project()
{
    local base_path=$1
    local projects_folder=$2

    vs2019_project_folder=$base_path/$projects_folder/vs2019
    if [ -d "$vs2019_project_folder" ] 
    then
        meson compile -C $vs2019_project_folder
        meson install --only-changed -C $vs2019_project_folder 
    fi
}



show_help() 
{
    script_name=$(basename "$0")
    echo "#######################################################################"
    echo "#                                                                     #"
    echo "#                        Project builder                              #"
    echo "#                                                                     #"
    echo "# USAGE:                                                              #"
    echo "#     $script_name {-h|--help | [--ninja] [--vs2019]}              #"
    echo "#                                                                     #"
    echo "# ARGUMENTS:                                                          #"
    echo "#     -h|--help    Print this help and exit.                          #"
    echo "#                                                                     #"
    echo "#     --ninja    Build Ninja projects.                                #"
    echo "#                                                                     #"
    echo "#     --vs2019    Build Visual Studio 2019 projects.                  #"
    echo "#                                                                     #"
    echo "#######################################################################"
}



command_line_args=("$@")
process_cmd ${command_line_args[@]}