#!/bin/bash



process_cmd()
{
    local show_help_arg=false
    local build_ninja_proj_arg=false
    local build_vs2019_proj_arg=false
    local total_args="$#"

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -h|--help) 
                show_help_arg=true 
            ;;
            --ninja)   
                build_ninja_proj_arg=true 
            ;;
            --vs2019)  
                build_vs2019_proj_arg=true 
            ;;
            *) 
                echo "An invalid parameter was provided: $1";
                exit 1 
            ;;
        esac
        shift
    done

    if [ $show_help_arg = true ] || [ $total_args -eq 0 ]
    then
        show_help
    elif [ $build_ninja_proj_arg = true ] || [ $build_vs2019_proj_arg = true ]
    then
        main $build_ninja_proj_arg $build_vs2019_proj_arg
    fi

    exit 0
}



main()
{
    local build_ninja_proj_arg=$1
    local build_vs2019_proj_arg=$2

    if [ $build_for_os = windows ]; then
        current_folder=`cygpath -w $current_folder`
    fi
    
    local projects_folder="projects"
    local artifact_folder="artifact"
    local base_path="${current_folder}build/$build_for_os/$build_for_arch/$build_for_type"
    
    if [ $build_ninja_proj_arg = true ]
    then
        build_ninja_proj $projects_folder $artifact_folder $base_path
    fi

    if [ $build_vs2019_proj_arg = true ]
    then
        build_vs2019_proj $projects_folder $artifact_folder $base_path
    fi
}



build_ninja_proj()
{
    local projects_folder=$1
    local artifact_folder=$2
    local base_path=$3

    ninja_project=$base_path/$projects_folder/ninja
    ninja_artifact=$base_path/$artifact_folder/ninja
    if [ -d "$ninja_project" ] 
    then
        ninja -C $base_path/$projects_folder/ninja
        meson install --only-changed -C $base_path/$projects_folder/ninja 
    fi
}



build_vs2019_proj()
{
    local projects_folder=$1
    local artifact_folder=$2
    local base_path=$3

    vs2019_project=$base_path/$projects_folder/vs2019
    vs2019_artifact=$base_path/$artifact_folder/vs2019
    if [ -d "$vs2019_project" ] 
    then
        pushd $base_path/$projects_folder/vs2019
            MSBuild.exe xcore.sln
            MSBuild.exe RUN_INSTALL.vcxproj
        popd
    fi
}



show_help() 
{
    script_name=$(basename "$0")
    echo "#######################################################################"
    echo "#                                                                     #"
    echo "#                        Project builder                              #"
    echo "#                                                                     #"
    echo "# USAGE:                                                              #"
    echo "#     $script_name {-h|--help | [--ninja] [--vs2019]}                  #"
    echo "#                                                                     #"
    echo "# ARGUMENTS:                                                          #"
    echo "#     -h|--help    Print this help and exit.                          #"
    echo "#                                                                     #"
    echo "#     --ninja    Build Ninja projects.                                #"
    echo "#                                                                     #"
    echo "#     --vs2019    Build Visual Studio 2019 projects.                  #"
    echo "#                                                                     #"
    echo "#######################################################################"
}



command_line_args=("$@")
process_cmd ${command_line_args[@]}