#!/bin/bash

process_cmd()
{
    local show_help_arg=false
    local workfolder_arg=""
    local config_file_arg=""
    local total_args=$#

    while [[ $# > 0 ]]; do
        case $1 in
            -h|--help)
                show_help_arg=true
            ;;
            --workfolder)
                shift
                workfolder_arg="$1"
            ;;
            --config-file)
                shift
                config_file_arg="$1"
            ;;
        esac
        shift
    done

    if [[ $show_help_arg == true ]] || [[ $total_args == 0 ]]
    then
        show_help
    else
        main
    fi

    exit 0
}


main()
{
    if [[ $build_for_os == windows ]]
    then
        workfolder_arg=`cygpath -u "$workfolder_arg"`
        config_file_arg=`cygpath -w "$config_file_arg"`
    fi

    pushd "$workfolder_arg"
        doxygen "$config_file_arg"
    popd
}


show_help()
{
    script_name=$(basename "$0")
    echo "#######################################################################"
    echo "#                                                                     #"
    echo "#                        DOXYGEN WRAPPER                              #"
    echo "#                                                                     #"
    echo "# USAGE:                                                              #"
    echo "#     $script_name {-h|--help | --workfolder path --config-file path} #"
    echo "#                                                                     #"
    echo "# ARGUMENTS:                                                          #"
    echo "#     -h|--help    Print this help and exit.                          #"
    echo "#                                                                     #"
    echo "#     --workfolder    The folder where doxygen commands will be       #"
    echo "#         executed.                                                   #"
    echo "#                                                                     #"
    echo "#     --config-file    Path to doxygen config file. OBS: Absolute or  #"
    echo "#         relative to workfolder.                                     #"
    echo "#                                                                     #"
    echo "#######################################################################"
}


command_line_args=("$@")
process_cmd ${command_line_args[@]}
